# For compiling the add-on packages.
# $Id: Makefile,v 1.1 2001/12/06 12:18:12 kaig Exp $

base64.elc: base64.el
	$(EMACS) -batch -f batch-byte-compile base64.el

format-spec.elc: format-spec.el
	$(EMACS) -batch -f batch-byte-compile format-spec.el

